Mng 16 create docker deploy
MongoTech/app pull request #1
Opened 2022-06-28 21:21 UTC by bvaliev

2022-06-30 19:46 UTC, dagolub requested changes

2022-06-30 19:46 UTC, dagolub commented on README.md
> +
тут все актуально?

2022-06-30 19:46 UTC, dagolub commented on backend/Dockerfile.arm64
> +FROM arm64v8/python:3.9 as requirements-stage
я перепилил базовые докер файлы пересмотри

2022-06-30 21:48 UTC, bvaliev commented on README.md
> +
да

2022-06-30 21:49 UTC, bvaliev commented on backend/Dockerfile.arm64
> +FROM arm64v8/python:3.9 as requirements-stage
ок. заменю начальные образы на `tiangolo/uvicorn-gunicorn-fastapi:python3.9`

2022-07-01 06:47 UTC, dagolub requested changes

2022-07-01 06:47 UTC, dagolub commented on backend/app/app/core/celery_app.py
> +MONGO_URL = f"{settings.MONGO_USER}:{settings.MONGO_PASS}@{settings.MONGO_HOST}:27017"
Так добавь порт раз ты его в констаныт вынкс

2022-07-01 06:47 UTC, dagolub commented on backend/app/app/db/session.py
> +MONGO_URL = f"{settings.MONGO_USER}:{settings.MONGO_PASS}@{settings.MONGO_HOST}:27017"
И сюда

2022-07-01 06:47 UTC, dagolub commented on docker-compose.dev.yml
> +      - "27017:27017"
тоже тогда брать из переменных окруженич

2022-07-02 12:31 UTC, dagolub approved these changes

2022-07-02 12:31 UTC, merged